/**
 * Sea Cadet Training Dashboard - Constants Module
 * Version: 1.0-RC2.40
 * Contains: Version, badge maps, syllabus data, rank orders, icons
 */

// Version
window.DATA_VERSION = "1.0-RC2.40"; // Modular file structure

// Badge & Rank Image Maps
window.RANK_IMG_MAP = {
    "Petty Officer Cadet": { sleeve: "scc_cadet_sleeve_petty_officer.webp", slide: "scc_cadet_shoulder_petty_officer.webp" },
    "Leading Cadet": { sleeve: "scc_cadet_sleeve_leading_cadet.webp", slide: "scc_cadet_shoulder_leading_cadet.webp" },
    "Able Cadet": { sleeve: "scc_cadet_sleeve_able_cadet.webp", slide: "scc_cadet_shoulder_able_cadet.webp" },
    "Ordinary Cadet": { sleeve: "scc_cadet_sleeve_ordinary_cadet.webp", slide: "scc_cadet_shoulder_ordinary_cadet.webp" },
    "Cadet 1st Class": { sleeve: "scc_cadet_sleeve_1st_class.webp", slide: "scc_cadet_shoulder_1st_class.webp" },
    "Cadet": { sleeve: "scc_cadet_sleeve_cadet.webp", slide: "scc_cadet_shoulder_cadet.webp" },
    "Cadet Sergeant": { sleeve: "rmc_rank_sergeant.webp", slide: "rmc_slide_cadet_sergeant.webp" },
    "Cadet Corporal": { sleeve: "rmc_rank_corporal.webp", slide: "rmc_slide_corporal.webp" },
    "Cadet Lance Corporal": { sleeve: "rmc_rank_lance_corporal.webp", slide: "rmc_slide_lance_corporal.webp" },
    "Marine Cadet": { sleeve: "rmc_rank_marine_cadet.webp", slide: "rmc_slide_marine_cadet.webp" }, 
    "Recruit": null,
    "New Entry Cadet": null,
    "Leading Junior Cadet": { sleeve: "scc_junior_leading.webp" },
    "Able Junior Cadet": { sleeve: "scc_junior_star.webp", count: 2 },
    "Junior Cadet 1st Class": { sleeve: "scc_junior_star.webp" },
    "Junior Cadet": { sleeve: "scc_junior_cadet.webp" }
};

window.BADGE_MAP = {
    "Drill - Advanced": "scc_prof_drill_advanced.webp",
    "Drill - Intermediate": "scc_prof_drill_intermediate.webp",
    "Drill - Basic": "scc_prof_drill_basic.webp",
    "Seamanship - Advanced": "scc_prof_seamanship_advanced.webp",
    "Seamanship - Intermediate": "scc_prof_seamanship_intermediate.webp",
    "Seamanship - Basic": "scc_prof_seamanship_basic.webp",
    "First Aid - Advanced": "scc_prof_first_aid_advanced.webp",
    "First Aid - Intermediate": "scc_prof_first_aid_intermediate.webp",
    "First Aid - Basic": "scc_prof_first_aid_basic.webp",
    "Marine Engineering - Advanced": "scc_prof_marine_eng_advanced.webp",
    "Marine Engineering Mechanical - Advanced": "scc_prof_me_mechanical_advanced.webp",
    "Marine Engineering Electrical - Advanced": "scc_prof_me_electrical_advanced.webp",
    "Marine Engineering - Intermediate": "scc_prof_marine_eng_intermediate.webp",
    "Marine Engineering - Basic": "scc_prof_marine_eng_basic.webp",
    "Navigation - Cadet Instructor": "scc_prof_navigation_instructor.webp",
    "Navigation - Advanced": "scc_prof_navigation_advanced.webp",
    "Navigation - Intermediate": "scc_prof_navigation_intermediate.webp",
    "Navigation - Basic": "scc_prof_navigation_basic.webp",
    "CIS Info Sys - Advanced": "scc_prof_cis_infosys_advanced.webp",
    "CIS Info Sys - Intermediate": "scc_prof_cis_infosys_intermediate.webp",
    "CIS Info Sys - Basic": "scc_prof_cis_infosys_basic.webp",
    "CIS Radio - Advanced": "scc_prof_cis_radio_advanced.webp",
    "CIS Radio - Intermediate": "scc_prof_cis_radio_intermediate.webp",
    "CIS Radio - Basic": "scc_prof_cis_infosys_basic.webp", 
    "CIS Principle Instructor": "scc_prof_cis_principle_instructor.webp",
    "Catering - Advanced": "scc_prof_catering_advanced.webp",
    "Catering - Intermediate": "scc_prof_catering_intermediate.webp",
    "Catering - Basic": "scc_prof_catering_basic.webp",
    "Stewarding - Advanced": "scc_prof_stewarding_advanced.webp",
    "Stewarding - Basic": "scc_prof_stewarding_basic.webp",
    "Physical Training - Instructor": "scc_prof_pt_instructor.webp",
    "Physical Training - Advanced": "scc_prof_pt_advanced.webp",
    "Physical Training - Intermediate": "scc_prof_pt_intermediate.webp",
    "Physical Training - Basic": "scc_prof_pt_basic.webp",
    "Rowing Instructor": "scc_prof_rowing_instructor.webp",
    "Rowing Coxswain": "scc_prof_rowing_coxswain.webp",
    "Rowing Supervised Coxswain": "scc_prof_rowing_supervised_cox.webp",
    "Rowing Competent Crew": "scc_prof_rowing_competent_crew.webp",
    "Powerboat Instructor": "scc_prof_powerboat_instructor.webp",
    "RYA Powerboat Intermediate": "scc_prof_powerboat_intermediate.webp",
    "RYA Safety Boat": "scc_prof_powerboat_safety.webp",
    "RYA Powerboat Level 2": "scc_prof_powerboat_level2.webp",
    "RYA Powerboat Level 1": "scc_prof_powerboat_level1.webp",
    "Paddlesport Instructor": "scc_prof_paddlesport_instructor.webp",
    "Paddle Discipline Specific": "scc_prof_paddle_specific.webp",
    "Paddle FSRT/PSRC": "scc_prof_paddle_fsrt.webp",
    "Paddle Explore Award": "scc_prof_paddle_explore.webp",
    "Paddle Discover Award": "scc_prof_paddle_discover.webp",
    "Dinghy Instructor": "scc_prof_sailing_dinghy_instructor.webp",
    "Spinnaker/Seamanship": "scc_prof_sailing_spinnaker.webp",
    "Sailing with Spinnakers": "scc_prof_sailing_spinnaker.webp",
    "Seamanship Skills": "scc_prof_sailing_spinnaker.webp",
    "Start Racing": "scc_prof_sailing_spinnaker.webp",
    "Performance Sailing": "scc_prof_sailing_spinnaker.webp",
    "Day Sailing": "scc_prof_sailing_spinnaker.webp",
    "Sailing Stage 4 / Level 3": "scc_prof_sailing_stage4.webp",
    "Sailing Stage 3 / Level 2": "scc_prof_sailing_stage3.webp",
    "Sailing Stage 2 / Level 1": "scc_prof_sailing_stage2.webp",
    "Windsurfing Instructor": "scc_prof_windsurfing_instructor.webp",
    "Windsurfing Stage 4": "scc_prof_windsurfing_stage4.webp",
    "Windsurfing Stage 3": "scc_prof_windsurfing_stage3.webp",
    "Windsurfing Stage 2": "scc_prof_windsurfing_stage2.webp",
    "Windsurfing Stage 1": "scc_prof_windsurfing_stage1.webp",
    "Master Coxswain": "scc_prof_master_coxswain.webp",
    "Cadet Coxswain": "scc_prof_cadet_coxswain.webp",
    "Offshore Power Watch Leader": "scc_prof_offshore_power_watch_leader.webp",
    "Offshore Power Seaman": "scc_prof_offshore_power_seaman.webp",
    "Offshore Power Grade 2": "scc_prof_offshore_power_grade2.webp",
    "Offshore Power Grade 1": "scc_prof_offshore_power_grade1.webp",
    "Offshore Sailing Watch Leader": "scc_prof_offshore_sailing_watch_leader.webp",
    "Offshore Sailing Seaman": "scc_prof_offshore_sailing_seaman.webp",
    "Offshore Sailing Grade 2": "scc_prof_offshore_sailing_grade2.webp",
    "Offshore Sailing Grade 1": "scc_prof_offshore_sailing_grade1.webp",
    "Campcraft (Advanced)": "scc_prof_campcraft_advanced.webp",
    "Campcraft (Intermediate)": "scc_prof_campcraft_intermediate.webp",
    "Campcraft (Basic)": "scc_prof_campcraft_basic.webp",
    "Climbing (Advanced)": "scc_prof_climbing_advanced.webp",
    "Climbing (Intermediate)": "scc_prof_climbing_intermediate.webp",
    "Climbing (Basic)": "scc_prof_climbing_basic.webp",
    "Mountain Biking (Advanced)": "scc_prof_mountain_biking_advanced.webp",
    "Mountain Biking (Intermediate)": "scc_prof_mountain_biking_intermediate.webp",
    "Mountain Biking (Basic)": "scc_prof_mountain_biking_basic.webp",
    "Semaphore": "scc_prof_semaphore.webp",
    "Radio Amateur": "scc_prof_radio_amateur.webp",
    "Morse Code": "scc_prof_morse.webp",
    "Meteorology": "scc_prof_meteorology.webp",
    "Air Rifle Marksman": "scc_prof_shooting_air_marksman.webp",
    "Air Rifle Advanced": "scc_prof_shooting_air_advanced.webp",
    "Air Rifle Basic": "scc_prof_shooting_air_basic.webp",
    "Small Bore Marksman": "scc_prof_shooting_smallbore_marksman.webp",
    "Small Bore Advanced": "scc_prof_shooting_smallbore_advanced.webp",
    "Small Bore Basic": "scc_prof_shooting_smallbore_basic.webp",
    "Full Bore Marksman": "scc_prof_shooting_fullbore_marksman.webp",
    "Full Bore Advanced": "scc_prof_shooting_fullbore_advanced.webp",
    "Full Bore Basic": "scc_prof_shooting_fullbore_basic.webp",
    "Bugler": "scc_prof_bugler.webp",
    "Musician": "scc_prof_musician.webp",
    "Drummer": "scc_prof_drummer.webp",
    "Diving (Cadet)": "scc_prof_diving.webp",
    "Piping Proficiency": "scc_prof_piping_proficiency.webp",
    "Piping Basic": "scc_prof_piping_basic.webp",
    "Wings (Standard)": "scc_award_wings_standard.png",
    "Gold Wings": "scc_award_wings_gold.png",
    "Silver Wings": "scc_award_wings_silver.png",
    "Bronze Wings": "scc_award_wings_bronze.png",
    "First Sea Lord's Cadet": "scc_award_first_sea_lords_cadet.webp",
    "Lord Lieutenant's Cadet": "scc_award_lord_lieutenants_cadet.webp",
    "Lord Mayor's Cadet": "scc_award_lord_mayors_cadet.webp",
    "Swim Test": "scc_swim.webp",
    "No Swim Test": "scc_NO_SWIM.webp",
    "Canada Trophy": "scc_award_canada_trophy.webp",
    "Commodore's Broad Pennant": "scc_award_commodores_pennant.webp",
    "DofE Gold": "scc_award_dofe_gold.webp",
    "DofE Silver": "scc_award_dofe_silver.webp",
    "DofE Bronze": "scc_award_dofe_bronze.webp",
    "BTEC Level 1": "scc_award_btec1.webp",
    "BTEC Level 2": "scc_award_btec2.webp",
    "Aviation Gold Wings": "scc_award_wings_gold.webp",
    "Aviation Silver Wings": "scc_award_wings_silver.webp",
    "Aviation Bronze Wings": "scc_award_wings_bronze.webp",
    "Aviation Wings (Standard)": "scc_award_wings_standard.webp",
    "SCC - JSC Red Unit Activities Badge": "scc_junior_section_red.webp",
    "SCC - JSC Blue Waterborne Activities Badge": "scc_junior_section_blue.webp",
    "SCC - JSC Green Outdoor & Recreation Activities Badge": "scc_junior_section_green.webp",
    "SCC - JSC Yellow Community & Citizenship Activities Badge": "scc_junior_section_yellow.webp",
    "SCC - JSC STEM Unit Activities Badge": "scc_junior_stem.webp",
    "SCC - JSC Commodores Broad Pennant": "scc_award_commodores_pennant.webp"
};

// Lucide Icons
window.Icons = {
    Upload: lucide.icons.Upload,
    Users: lucide.icons.Users,
    Award: lucide.icons.Award,
    BookOpen: lucide.icons.BookOpen,
    CheckCircle: lucide.icons.CheckCircle,
    FileText: lucide.icons.FileText,
    ChevronDown: lucide.icons.ChevronDown,
    ChevronUp: lucide.icons.ChevronUp,
    ChevronLeft: lucide.icons.ChevronLeft,
    ChevronRight: lucide.icons.ChevronRight,
    Calendar: lucide.icons.Calendar,
    Save: lucide.icons.Save,
    Trash2: lucide.icons.Trash2,
    RefreshCw: lucide.icons.RefreshCw,
    X: lucide.icons.X,
    AlertCircle: lucide.icons.AlertCircle,
    Anchor: lucide.icons.Anchor,
    Shield: lucide.icons.Shield,
    ShieldAlert: lucide.icons.ShieldAlert,
    Target: lucide.icons.Target,
    Lightbulb: lucide.icons.Lightbulb,
    User: lucide.icons.User,
    Star: lucide.icons.Star,
    Command: lucide.icons.Command,
    ShipWheel: lucide.icons.ShipWheel,
    ChartGantt: lucide.icons.ChartGantt,
    Database: lucide.icons.Database,
    Download: lucide.icons.Download,
    Settings: lucide.icons.Settings,
    BarChart3: lucide.icons.BarChart3,
    Home: lucide.icons.Home
};

// Rank Orders
window.SCC_RANK_ORDER = ["New Entry Cadet", "Cadet", "Cadet 1st Class", "Ordinary Cadet", "Able Cadet", "Leading Cadet", "Petty Officer Cadet"];
window.RMC_RANK_ORDER = ["Recruit", "Marine Cadet", "Cadet Lance Corporal", "Cadet Corporal", "Cadet Sergeant"];
window.JUNIOR_RANK_ORDER = ["Junior Cadet", "Junior Cadet 1st Class", "Able Junior Cadet", "Leading Junior Cadet"];

// Rank Abbreviations
window.RANK_ABBREVIATIONS = {
    "Petty Officer Cadet": "POC",
    "Leading Cadet": "LC",
    "Able Cadet": "AC",
    "Ordinary Cadet": "OC",
    "Cadet 1st Class": "Cdt 1st",
    "Cadet": "Cdt",
    "New Entry Cadet": "NEC",
    "Leading Junior Cadet": "LJC",
    "Able Junior Cadet": "AJC",
    "Junior Cadet 1st Class": "JCFC",
    "Junior Cadet": "JC",
    "Cadet Sergeant": "Cdt Sgt",
    "Cadet Corporal": "Cdt Cpl",
    "Cadet Lance Corporal": "Cdt LCpl",
    "Marine Cadet": "MC",
    "Recruit": "Rct"
};

console.log("✓ Constants module loaded");
